### ISSUE TITLE
Heading

### ISSUE THREAD

**Issue by lvafi** [victorsalmon/aloha#2]
h5 tag in HTML code directly following an h2. In order to maintain a consistent outline of the page for assistive technologies, reduce the gap in the heading level by upgrading this tag to an h3 or h2.

**Comment by lvafi** [comment]
<h5> tag in HTML code directly following an <h2>. In order to maintain a consistent outline of the page for assistive technologies, reduce the gap in the heading level by upgrading this tag to an <h3> or <h2>.
<h5>Dresses</h5>

**Comment by victorsalmon** [comment]
Patched in Commit 60 on May 3rd
https://github.com/victorsalmon/aloha/commit/6b1e7cfa686a6a36ad0d0f08f8305785ff3ba6ed
